---
- hosts: all
  become: yes
  tasks:
    - name: install nginx application
      apt:
        name: nginx
        state: present
      when: ansible_os_family in ["Debian"] 
    - name: install nginx in amazon ec2
      yum:
        name: nginx
        state: present
      when: ansible_os_family in ["RedHat"]
    - name: start the application
      service:
        name: nginx
        state: started
    - name: copy custom file 
      copy:
        src: "/root/index.html"
        dest: "/var/www/html/index.html"
      when: ansible_os_family in ["Debian"]
      notify: 
        - restart nginx
    - name: copy custom file ansible master to redhat
      copy:
        src: "/root/index.html"
        dest: "/usr/share/nginx/html/index.html"
      when: ansible_os_family in ["RedHat"]
      notify:
        - restart nginx
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
